apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: cli-plugin-plugins
  description: Enable users to install plugins in the VTEX CLI
  tags:
    - typescript
    - oclif
    - plugin
  annotations:
    vtex.com/janus-acronym: ""
    vtex.com/o11y-os-index: ""
    grafana/dashboard-selector: ""
    github.com/project-slug: vtex/cli-plugin-plugins
    backstage.io/techdocs-ref: dir:../
spec:
  lifecycle: stable
  owner: apps
  type: cli
  dependsOn:
    - component:toolbelt
