- name: cli-plugin-plugins
  referenceId: PLACEHOLDER
  build:
    provider: dkcicd
    pipelines:
      - name: node-ci-v2
        parameters:
          sonarProjectName: cli-plugin-plugins
          nodeVersion: 20-bookworm
          nodeCommands:
            - test
        runtime:
          architecture: amd64
        when:
          - event: pull_request
            source: branch
          - event: push
            source: branch
            regex: main
      - name: techdocs-v1
        parameters:
          entityReference: default/component/cli-plugin-plugins
          sourceDir: ./
        when:
          - event: push
            source: branch
            regex: main
            path:
              - "docs/**"
              - README.md
              - .vtex/deployment.yaml