name: publish-prerelease:npm

on:
  push:
    branches-ignore:
      - '**'
    tags:
      - 'v[0-9]+.[0-9]+.[0-9]+-beta*'

jobs:
  npm-publish:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: 12
          registry-url: https://registry.npmjs.org/
      - run: yarn
      - name: Read package.json
        id: package
        uses: juliangruber/read-file-action@v1.0.0
        with:
          path: ./oclif.manifest.json
      - run: echo ${{ steps.package.outputs.content }}
      - run: npm publish --access=public --tag beta
        env:
          NODE_AUTH_TOKEN: ${{secrets.NPM_TOKEN}}
          IS_CI: 'true'
